### ISSUE TITLE
Module top cover STL

### ISSUE THREAD

**Issue by giulianob** [UltimateHackingKeyboard/cad#1]
Any chance you can provide the STL files for the top trackpoint cover? The mouse button has broken twice for me now. It seems the plastic clip where it connects to the module just wears out over time and breaks. You provided a replacement the first time it broke but seems this is a design issue and I'm wondering if I could get the STL to try and print it myself instead of ordering one which would cost over $30 with shipping. Thank you!

**Comment by mondalaci** [comment]
Per our policy, we plan to publish UHK mechanical files per part after obsolete parts are no longer produced or stocked.

If your replacement part is under warranty, then we can provide it for free, in which case please contact support at ultimatehackingkeyboard dot com.

**Comment by mondalaci** [comment]
I also want to add that this is an infrequent issue for most. I'm sorry it affects you more.
